language: go

go:
  - 1.10.x

env:
  - DAP_EXECUTABLE=godap

before_install:
 - git clone https://github.com/sstephenson/bats.git
 - cd bats
 - sudo ./install.sh /usr
 - cd ..
 - rm -r bats

script: 
  - go test -v ./...
  - find . -name \*.bats | grep -v test/test_helper/ | xargs -n1 bats
